spring:
  datasource:
    url: jdbc:h2:mem:testdb
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true